/* =========================================================
   えいごクラフト 5きゅう - dialogue-data.js

   大もん2(会話文の文空所補充)・リスニング第1部(会話の応答文選択)・
   第2部(会話の内容一致選択)の れんしゅうよう データ。

   ぜんぶ オリジナルで かいた 会話文です。ほんばんの 過去問は
   きょうかいが「複製・漏えい(ネットへの けいさいを ふくむ)を きんじる」と
   はっきり しめしているため、このアプリには 一字一句 うつしていません。
   出題の「かたち」(なんぎょうの 会話か、なんこの せんたくしか)だけを
   ほんばんに あわせ、なかみは ぜんぶ 新規に かいています。
   ========================================================= */

/* ---------- 大もん2: 会話文の文空所補充 ----------
   A の はつげんに つづく B の こたえの ( ) を うめる。
   a: A の せりふ、after: ( )の あとに つづく きまった 文(なければ "")、
   correct/correctJa: せいかいの こたえと いみ、wrongs: まちがいの こたえ3つ */
const DAIMON2_POOL = [
  { a: "Are you free this afternoon?", after: "I have piano practice.",
    correct: "No, I'm not.", correctJa: "ううん、ひまじゃないよ。",
    wrongs: ["Yes, please.", "You're welcome.", "Nice to meet you."] },
  { a: "Do you have any questions?", after: "",
    correct: "No, I don't.", correctJa: "いいえ、ありません。",
    wrongs: ["Yes, please.", "I'm eight years old.", "It's Monday."] },
  { a: "I like your new bag.", after: "",
    correct: "Thank you.", correctJa: "ありがとう。",
    wrongs: ["I'm sorry.", "Me, too.", "Not yet."] },
  { a: "Excuse me, is this seat free?", after: "",
    correct: "Yes, it is.", correctJa: "はい、あいてます。",
    wrongs: ["I don't know him.", "It's five o'clock.", "That's too bad."] },
  { a: "Let's play soccer after school.", after: "",
    correct: "Sounds good.", correctJa: "いいね。",
    wrongs: ["I'm sorry to hear that.", "You're welcome.", "See you."] },
  { a: "Can I borrow your pencil?", after: "Here you are.",
    correct: "Sure.", correctJa: "いいよ。",
    wrongs: ["No, thanks.", "I don't know.", "Not really."] },
  { a: "Did you finish your homework?", after: "",
    correct: "Not yet.", correctJa: "まだだよ。",
    wrongs: ["It's raining.", "I'm eight.", "See you tomorrow."] },
  { a: "How many pens do you have?", after: "",
    correct: "I have three.", correctJa: "3本 もってるよ。",
    wrongs: ["I like blue.", "It's on the desk.", "Yes, I do."] },
  { a: "What time is it now?", after: "",
    correct: "It's noon.", correctJa: "ちょうど お昼だよ。",
    wrongs: ["It's Friday.", "I'm fine.", "I have two."] },
  { a: "Whose bag is this?", after: "",
    correct: "It's mine.", correctJa: "わたしのだよ。",
    wrongs: ["It's blue.", "I'm ten.", "That's right."] },
  { a: "Do you want some tea?", after: "",
    correct: "Yes, please.", correctJa: "うん、ください。",
    wrongs: ["I'm sorry.", "Nice to meet you.", "That's too bad."] },
  { a: "I can't find my key.", after: "",
    correct: "That's too bad.", correctJa: "それは たいへんだね。",
    wrongs: ["Good idea.", "Congratulations.", "You're welcome."] },
  { a: "Thank you for the present.", after: "",
    correct: "You're welcome.", correctJa: "どういたしまして。",
    wrongs: ["Thank you, too.", "I'm sorry.", "Not really."] },
  { a: "I'm sorry I'm late.", after: "",
    correct: "That's OK.", correctJa: "だいじょうぶだよ。",
    wrongs: ["Me, too.", "I don't think so.", "Good job."] },
  { a: "Where do you want to go this weekend?", after: "",
    correct: "I want to go to the zoo.", correctJa: "どうぶつえんに 行きたいな。",
    wrongs: ["I have two sisters.", "It's Tuesday.", "Yes, I can."] },
  { a: "Which bag is yours, the red one or the blue one?", after: "",
    correct: "The blue one is mine.", correctJa: "青いのが わたしのだよ。",
    wrongs: ["It's under the table.", "I'm fine, thanks.", "That's right."] },
  { a: "Why are you so happy today?", after: "",
    correct: "Because it's my birthday.", correctJa: "だって たんじょうびだから。",
    wrongs: ["At six o'clock.", "Near the station.", "By bus."] },
  { a: "How do you go to school?", after: "",
    correct: "I go by bike.", correctJa: "じてんしゃで 行くよ。",
    wrongs: ["I go with Ken.", "I have three.", "Yes, it is."] },
  { a: "Is this your notebook?", after: "",
    correct: "No, it isn't.", correctJa: "ううん、ちがうよ。",
    wrongs: ["Yes, please.", "I'm sorry to hear that.", "Not yet."] },
  { a: "Happy birthday, Tom!", after: "",
    correct: "Thanks a lot.", correctJa: "ありがとう!",
    wrongs: ["Me, too.", "Not at all.", "See you."] },
  { a: "Do you often watch TV at night?", after: "",
    correct: "No, I usually read books.", correctJa: "ううん、たいてい 本を よむよ。",
    wrongs: ["It's white.", "I'm nine.", "By train."] },
  { a: "Can you close the window, please?", after: "",
    correct: "Sure, Mom.", correctJa: "いいよ、おかあさん。",
    wrongs: ["I like it.", "That's right.", "See you soon."] },
  { a: "Is your father a teacher?", after: "",
    correct: "No, he's a doctor.", correctJa: "ううん、おいしゃさんだよ。",
    wrongs: ["Yes, please.", "It's cloudy.", "I have one."] },
  { a: "Nice to meet you.", after: "",
    correct: "Nice to meet you, too.", correctJa: "こちらこそ、はじめまして。",
    wrongs: ["You're welcome.", "That's too bad.", "I'm sorry."] },
];

/* ---------- リスニング第1部: 会話の応答文選択 ----------
   1つの はつげんを きいて、いちばん あう こたえを 3つから えらぶ。
   えいごの もじは 出さない(きくだけで こたえる)。 */
const LISTEN1_POOL = [
  { prompt: "How are you today?", promptJa: "きょうの ちょうしは どう?",
    correct: "I'm fine, thank you.", correctJa: "げんきだよ、ありがとう。",
    wrongs: ["It's five o'clock.", "I have two dogs."] },
  { prompt: "What's your name?", promptJa: "なまえは なに?",
    correct: "My name is Emma.", correctJa: "わたしは エマだよ。",
    wrongs: ["I'm ten years old.", "It's on the table."] },
  { prompt: "Do you like apples?", promptJa: "りんご すき?",
    correct: "Yes, I do.", correctJa: "うん、すきだよ。",
    wrongs: ["I'm from Japan.", "It's Monday."] },
  { prompt: "See you tomorrow!", promptJa: "また あした!",
    correct: "See you!", correctJa: "またね!",
    wrongs: ["Nice to meet you.", "I'm sorry."] },
  { prompt: "Can you help me, please?", promptJa: "てつだって くれる?",
    correct: "Sure, no problem.", correctJa: "うん、いいよ。",
    wrongs: ["That's too bad.", "Happy birthday."] },
  { prompt: "Where is the library?", promptJa: "としょかんは どこ?",
    correct: "It's near the park.", correctJa: "こうえんの ちかくだよ。",
    wrongs: ["I'm fine, thanks.", "At seven o'clock."] },
  { prompt: "How old are you?", promptJa: "なんさい?",
    correct: "I'm nine.", correctJa: "9さいだよ。",
    wrongs: ["I'm from Canada.", "It's rainy."] },
  { prompt: "Whose umbrella is this?", promptJa: "これ だれの かさ?",
    correct: "It's mine.", correctJa: "わたしのだよ。",
    wrongs: ["It's red.", "At the door."] },
  { prompt: "What time do you get up?", promptJa: "なんじに おきるの?",
    correct: "I get up at seven.", correctJa: "7じに おきるよ。",
    wrongs: ["I like milk.", "It's my bag."] },
  { prompt: "Thank you very much.", promptJa: "どうも ありがとう。",
    correct: "You're welcome.", correctJa: "どういたしまして。",
    wrongs: ["I'm sorry.", "Not yet."] },
  { prompt: "Is it raining outside?", promptJa: "そと あめ ふってる?",
    correct: "Yes, it is.", correctJa: "うん、ふってるよ。",
    wrongs: ["I'm eight.", "It's blue."] },
  { prompt: "What do you want for lunch?", promptJa: "おひるごはんは なにが いい?",
    correct: "I want pizza.", correctJa: "ピザが いいな。",
    wrongs: ["I'm at school.", "On Sunday."] },
  { prompt: "Let's go to the park.", promptJa: "こうえんに いこう。",
    correct: "OK, let's go.", correctJa: "うん、いこう。",
    wrongs: ["I'm sorry to hear that.", "You're welcome."] },
  { prompt: "How many brothers do you have?", promptJa: "おとうと・おにいさんは なんにん?",
    correct: "I have one brother.", correctJa: "ひとり いるよ。",
    wrongs: ["I like soccer.", "It's cold today."] },
  { prompt: "Where are you from?", promptJa: "出身は どこ?",
    correct: "I'm from Osaka.", correctJa: "おおさか出身だよ。",
    wrongs: ["It's three o'clock.", "I have a cat."] },
  { prompt: "Is your sister a student?", promptJa: "おねえさんは 学生?",
    correct: "Yes, she is.", correctJa: "うん、そうだよ。",
    wrongs: ["It's sunny.", "I'm ten."] },
  { prompt: "What's the weather like today?", promptJa: "きょうの てんきは?",
    correct: "It's cloudy.", correctJa: "くもりだよ。",
    wrongs: ["I'm fine.", "At the station."] },
  { prompt: "Do you play the piano?", promptJa: "ピアノ ひく?",
    correct: "Yes, every day.", correctJa: "うん、まいにち ひくよ。",
    wrongs: ["It's my pen.", "I'm from Kyoto."] },
  { prompt: "Sorry, I'm late.", promptJa: "ごめん、おくれた。",
    correct: "That's OK.", correctJa: "だいじょうぶだよ。",
    wrongs: ["Good idea.", "Congratulations."] },
  { prompt: "What day is it today?", promptJa: "きょうは 何曜日?",
    correct: "It's Wednesday.", correctJa: "水曜日だよ。",
    wrongs: ["It's nine o'clock.", "I'm happy."] },
  { prompt: "Can I use your phone?", promptJa: "でんわ かりても いい?",
    correct: "Sorry, I don't have one.", correctJa: "ごめん、もってないんだ。",
    wrongs: ["Yes, I can.", "It's Friday."] },
  { prompt: "How do you come to school?", promptJa: "がっこうまで どうやって くるの?",
    correct: "I walk to school.", correctJa: "あるいて くるよ。",
    wrongs: ["I have two pens.", "It's my book."] },
  { prompt: "Do you have any pets?", promptJa: "ペット かってる?",
    correct: "Yes, I have a dog.", correctJa: "うん、いぬを かってるよ。",
    wrongs: ["I'm in the kitchen.", "It's four o'clock."] },
  { prompt: "Nice to meet you.", promptJa: "はじめまして。",
    correct: "Nice to meet you, too.", correctJa: "こちらこそ、はじめまして。",
    wrongs: ["Good night.", "You're welcome."] },
];

/* ---------- リスニング第2部: 会話の内容一致選択 ----------
   2ぎょうの 会話 + しつもんを きいて、ないように あう こたえを
   4つの もじの せんたくしから えらぶ(せんたくしだけは 見える)。 */
const LISTEN2_POOL = [
  { a: "Ken, what do you have for breakfast?", b: "I have rice and eggs, Mom.",
    q: "What does Ken have for breakfast?", qJa: "ケンは 朝ごはんに なにを 食べる?",
    correct: "Rice and eggs.",
    wrongs: ["Bread and milk.", "Soup and salad.", "Fish and rice balls."] },
  { a: "Do you want to go to the zoo or the museum, Emma?", b: "I want to go to the zoo.",
    q: "Where does Emma want to go?", qJa: "エマは どこに 行きたい?",
    correct: "To the zoo.",
    wrongs: ["To the museum.", "To the park.", "To the library."] },
  { a: "Mike, how many cats do you have?", b: "I have two cats and one dog.",
    q: "How many cats does Mike have?", qJa: "マイクは ねこを 何びき かってる?",
    correct: "Two.",
    wrongs: ["One.", "Three.", "None."] },
  { a: "Lisa, what time does your class start?", b: "It starts at nine o'clock.",
    q: "What time does Lisa's class start?", qJa: "リサの じゅぎょうは 何じから?",
    correct: "At nine o'clock.",
    wrongs: ["At eight o'clock.", "At ten o'clock.", "At noon."] },
  { a: "Tom, is your father a doctor?", b: "No, he's a teacher.",
    q: "What is Tom's father?", qJa: "トムの おとうさんの しごとは?",
    correct: "A teacher.",
    wrongs: ["A doctor.", "A nurse.", "A student."] },
  { a: "Kate, what's your favorite sport?", b: "I like tennis the best.",
    q: "What is Kate's favorite sport?", qJa: "ケイトが いちばん すきな スポーツは?",
    correct: "Tennis.",
    wrongs: ["Soccer.", "Baseball.", "Swimming."] },
  { a: "Jack, where is your bag?", b: "It's under the chair.",
    q: "Where is Jack's bag?", qJa: "ジャックの かばんは どこ?",
    correct: "Under the chair.",
    wrongs: ["On the chair.", "Under the table.", "In the box."] },
  { a: "Amy, whose pencil case is this?", b: "It's my brother's.",
    q: "Whose pencil case is it?", qJa: "だれの ふでばこ?",
    correct: "Amy's brother's.",
    wrongs: ["Amy's.", "Amy's sister's.", "Amy's teacher's."] },
  { a: "Sam, how do you go to the station?", b: "I usually go by bus.",
    q: "How does Sam usually go to the station?", qJa: "サムは どうやって えきに 行く?",
    correct: "By bus.",
    wrongs: ["By bike.", "By train.", "On foot."] },
  { a: "Ben, do you often play video games?", b: "Yes, I play them every weekend.",
    q: "When does Ben play video games?", qJa: "ベンは いつ ゲームを する?",
    correct: "Every weekend.",
    wrongs: ["Every morning.", "Every day.", "Every Monday."] },
  { a: "Nancy, what color is your new bike?", b: "It's yellow.",
    q: "What color is Nancy's new bike?", qJa: "ナンシーの あたらしい じてんしゃの 色は?",
    correct: "Yellow.",
    wrongs: ["Blue.", "Red.", "Green."] },
  { a: "Paul, how old is your grandmother?", b: "She is sixty-five.",
    q: "How old is Paul's grandmother?", qJa: "ポールの おばあさんは 何さい?",
    correct: "Sixty-five.",
    wrongs: ["Fifty-five.", "Seventy-five.", "Forty-five."] },
  { a: "Sara, what do you usually drink in the morning?", b: "I usually drink orange juice.",
    q: "What does Sara usually drink in the morning?", qJa: "サラは 朝 いつも なにを のむ?",
    correct: "Orange juice.",
    wrongs: ["Milk.", "Tea.", "Water."] },
  { a: "Alex, which season do you like the best?", b: "I like winter the best.",
    q: "Which season does Alex like the best?", qJa: "アレックスが いちばん すきな きせつは?",
    correct: "Winter.",
    wrongs: ["Summer.", "Spring.", "Fall."] },
  { a: "Emily, where do you study every night?", b: "I study in my room.",
    q: "Where does Emily study every night?", qJa: "エミリーは まいばん どこで べんきょうする?",
    correct: "In her room.",
    wrongs: ["In the kitchen.", "In the living room.", "At the library."] },
  { a: "David, what day do you have music class?", b: "I have it on Thursday.",
    q: "What day does David have music class?", qJa: "デイビッドの おんがくの じゅぎょうは 何曜日?",
    correct: "Thursday.",
    wrongs: ["Tuesday.", "Wednesday.", "Friday."] },
  { a: "Olivia, how many books do you read every month?", b: "I read about four books.",
    q: "How many books does Olivia read every month?", qJa: "オリビアは 1か月に 何さつ 本を よむ?",
    correct: "About four.",
    wrongs: ["About two.", "About six.", "About eight."] },
  { a: "Kevin, who is your best friend?", b: "Jim is my best friend.",
    q: "Who is Kevin's best friend?", qJa: "ケビンの いちばんの ともだちは だれ?",
    correct: "Jim.",
    wrongs: ["Tom.", "Ben.", "Sam."] },
  { a: "Hana, what is your mother's job?", b: "She is a nurse.",
    q: "What is Hana's mother's job?", qJa: "ハナの おかあさんの しごとは?",
    correct: "A nurse.",
    wrongs: ["A teacher.", "A doctor.", "A cook."] },
  { a: "Leo, when is your birthday?", b: "It's in May.",
    q: "When is Leo's birthday?", qJa: "レオの たんじょうびは いつ?",
    correct: "In May.",
    wrongs: ["In April.", "In June.", "In March."] },
];

/* ---------- 大もん1: 短文の語句空所補充(単語1つの あなうめ) ----------
   本番の 大もん1と おなじ かたち。会話1〜2ぎょう、または みじかい
   ぶん(2文まで)の なかの ( ) に 入る ことばを、おなじ ひんし(名詞
   どうしなど)の 4つの せんたくしから えらぶ。ぶんの いみが わからないと
   えらべない ように、まちがいの せんたくしは 1つずつ てで えらんである。

   pre  : あなの まえに くる せりふ(はなし手あり)の はいれつ
   blankSpeaker: あなの ある ぎょうの はなし手("A"/"B"/null)
   before/after: あなの まえ/あとの もじ(かっこは ふくまない)
   post : あなの あとに くる せりふの はいれつ

   ぜんぶ オリジナルで かいた もんだいです(著作権の ことは
   dialogue-data.js の さいしょの コメントを 見てね)。 */
const DAIMON1_POOL = [
  { pre: [{ speaker: "A", text: "What are you doing, Aki?" }],
    blankSpeaker: "B",
    before: "I'm looking for my", after: ". I can't find it anywhere.",
    post: [],
    correct: "glasses", correctJa: "めがね",
    fullJa: "なにしてるん、アキ? めがねを さがしてるの。どこにも 見あたらなくて。",
    wrongs: ["weather", "answer", "song"] },
  { pre: [{ speaker: "A", text: "Why is your dog barking so much, Leo?" }],
    blankSpeaker: "B",
    before: "A cat is in our", after: ".",
    post: [],
    correct: "garden", correctJa: "にわ",
    fullJa: "なんで そんなに ワンちゃん ほえてるの? ねこが うちの にわに いるから。",
    wrongs: ["notebook", "language", "answer"] },
  { pre: [],
    blankSpeaker: "A",
    before: "Mom, I'm thirsty. Can I have some", after: "?",
    post: [{ speaker: "B", text: "Sure, here you are." }],
    correct: "juice", correctJa: "ジュース",
    fullJa: "おかあさん、のどが かわいたの。ジュース もらえる? いいよ、はい どうぞ。",
    wrongs: ["scissors", "shoes", "keys"] },
  { pre: [{ speaker: "A", text: "What's wrong, Nina?" }],
    blankSpeaker: "B",
    before: "I dropped my phone, and now the screen is", after: ".",
    post: [],
    correct: "broken", correctJa: "こわれた",
    fullJa: "どうしたの、ニーナ? けいたい おとしちゃって、がめんが こわれちゃったの。",
    wrongs: ["sleepy", "busy", "delicious"] },
  { pre: [{ speaker: "A", text: "How was the soccer game, Jack?" }],
    blankSpeaker: "B",
    before: "We", after: "3 to 1. It was great!",
    post: [],
    correct: "won", correctJa: "かった",
    fullJa: "サッカーの しあい どうだった、ジャック? 3対1で かったよ。さいこうだった!",
    wrongs: ["cooked", "cleaned", "painted"] },
  { pre: [{ speaker: "A", text: "Are you ready for the school festival, Miki?" }],
    blankSpeaker: "B",
    before: "Almost. I need to finish my", after: "first.",
    post: [],
    correct: "costume", correctJa: "いしょう",
    fullJa: "がっこうの おまつりの じゅんび できた、ミキ? もうすぐ。さきに いしょうを しあげなきゃ。",
    wrongs: ["umbrella", "medicine", "map"] },
  { pre: [{ speaker: "A", text: "Why are you wet, Danny?" }],
    blankSpeaker: "B",
    before: "It started to", after: "on my way home.",
    post: [],
    correct: "rain", correctJa: "あめが ふる",
    fullJa: "なんで ぬれてるの、ダニー? かえりみちで あめが ふりだしたんだ。",
    wrongs: ["shine", "sing", "cook"] },
  { pre: [],
    blankSpeaker: "A",
    before: "Grandma, can you", after: "me a story tonight?",
    post: [{ speaker: "B", text: "Of course, sweetie." }],
    correct: "tell", correctJa: "はなす",
    fullJa: "おばあちゃん、こんばん おはなし してくれる? もちろんよ。",
    wrongs: ["cut", "wash", "carry"] },
  { pre: [{ speaker: "A", text: "Where's your little brother, Yuna?" }],
    blankSpeaker: "B",
    before: "He's taking a", after: "in the bathroom.",
    post: [],
    correct: "bath", correctJa: "おふろ",
    fullJa: "おとうとくんは どこ、ユナ? おふろばで おふろに はいってるよ。",
    wrongs: ["photo", "test", "trip"] },
  { pre: [{ speaker: "A", text: "This soup smells wonderful." }],
    blankSpeaker: "B",
    before: "Thank you. I put a lot of", after: "in it.",
    post: [],
    correct: "vegetables", correctJa: "やさい",
    fullJa: "この スープ すごく いい におい。ありがとう。やさいを たくさん 入れたの。",
    wrongs: ["pillows", "erasers", "batteries"] },
  { pre: [],
    blankSpeaker: null,
    before: "My cousin visits us", after: "summer. We always go to the beach together.",
    post: [],
    correct: "every", correctJa: "まいとし",
    fullJa: "いとこは まいとし なつに あそびに くる。いつも いっしょに うみに いく。",
    wrongs: ["some", "any", "no"] },
  { pre: [],
    blankSpeaker: "A",
    before: "Do you know", after: "this bicycle is, Ryo?",
    post: [{ speaker: "B", text: "It's my sister's." }],
    correct: "whose", correctJa: "だれの",
    fullJa: "この じてんしゃ だれの か しってる、リョウ? わたしの いもうとの だよ。",
    wrongs: ["what", "when", "why"] },
  { pre: [],
    blankSpeaker: "A",
    before: "The stars are so", after: "tonight, aren't they?",
    post: [{ speaker: "B", text: "Yes, let's take a picture." }],
    correct: "beautiful", correctJa: "きれい",
    fullJa: "こんばんの ほし すごく きれいだね。うん、しゃしん とろう。",
    wrongs: ["hungry", "angry", "noisy"] },
  { pre: [{ speaker: "A", text: "Can you help me carry these boxes, Sota?" }],
    blankSpeaker: "B",
    before: "Sure. Are they", after: "?",
    post: [],
    correct: "heavy", correctJa: "おもい",
    fullJa: "この はこ はこぶの てつだって、ソウタ。いいよ。おもいの?",
    wrongs: ["kind", "loud", "cheap"] },
  { pre: [],
    blankSpeaker: "A",
    before: "What time does the movie", after: ", Hana?",
    post: [{ speaker: "B", text: "It starts at seven." }],
    correct: "start", correctJa: "はじまる",
    fullJa: "えいが なんじに はじまるの、ハナ? 7じに はじまるよ。",
    wrongs: ["draw", "cry", "smell"] },
  { pre: [{ speaker: "A", text: "I'm making a birthday cake for Dad." }],
    blankSpeaker: "B",
    before: "Can I", after: "you?",
    post: [],
    correct: "help", correctJa: "てつだう",
    fullJa: "おとうさんの たんじょうびケーキ つくってるの。てつだっても いい?",
    wrongs: ["hear", "wear", "catch"] },
  { pre: [],
    blankSpeaker: "A",
    before: "Where do you keep your", after: ", Ellie?",
    post: [{ speaker: "B", text: "In the top drawer." }],
    correct: "socks", correctJa: "くつした",
    fullJa: "くつした どこに しまってるの、エリー? いちばん うえの ひきだしだよ。",
    wrongs: ["oceans", "clouds", "mountains"] },
  { pre: [],
    blankSpeaker: "A",
    before: "How many", after: "does your school have, Kai?",
    post: [{ speaker: "B", text: "About six hundred." }],
    correct: "students", correctJa: "せいと",
    fullJa: "きみの がっこう せいとは なんにん、カイ? やく600にんだよ。",
    wrongs: ["clouds", "windows", "rivers"] },
  { pre: [{ speaker: "A", text: "Did you enjoy the camping trip, Rin?" }],
    blankSpeaker: "B",
    before: "Yes! We saw so many", after: "in the sky.",
    post: [],
    correct: "stars", correctJa: "ほし",
    fullJa: "キャンプ たのしかった、リン? うん!そらに たくさん ほしが 見えたよ。",
    wrongs: ["shoes", "chairs", "spoons"] },
  { pre: [],
    blankSpeaker: "A",
    before: "This math problem is really", after: "for me.",
    post: [{ speaker: "B", text: "Let me help you." }],
    correct: "difficult", correctJa: "むずかしい",
    fullJa: "この さんすうの もんだい ほんとに むずかしいよ。てつだうよ。",
    wrongs: ["delicious", "friendly", "windy"] },
  { pre: [{ speaker: "A", text: "I heard you have a new pet, Owen." }],
    blankSpeaker: "B",
    before: "Yes, it's a small orange", after: ".",
    post: [],
    correct: "fish", correctJa: "さかな",
    fullJa: "あたらしい ペット かってるんだって、オーウェン。うん、ちいさい オレンジいろの さかなだよ。",
    wrongs: ["chair", "pillow", "spoon"] },
  { pre: [],
    blankSpeaker: "A",
    before: "Can we", after: "the piano together, Maya?",
    post: [{ speaker: "B", text: "I'd love to!" }],
    correct: "play", correctJa: "ひく",
    fullJa: "いっしょに ピアノ ひこうか、マヤ? ぜひ!",
    wrongs: ["cut", "wash", "wear"] },
  { pre: [],
    blankSpeaker: "A",
    before: "I lost one of my", after: "at the park.",
    post: [{ speaker: "B", text: "That's too bad. Let's go look for it." }],
    correct: "gloves", correctJa: "てぶくろ",
    fullJa: "こうえんで てぶくろ かたっぽ なくしちゃった。それは たいへん。さがしに いこう。",
    wrongs: ["ideas", "answers", "colors"] },
  { pre: [],
    blankSpeaker: "A",
    before: "What time do you usually go to", after: ", Ben?",
    post: [{ speaker: "B", text: "Around nine thirty." }],
    correct: "bed", correctJa: "ねる",
    fullJa: "いつも なんじに ねるの、ベン? だいたい 9じはんだよ。",
    wrongs: ["water", "music", "money"] },
  { pre: [{ speaker: "A", text: "How do you feel today, Grandpa?" }],
    blankSpeaker: "B",
    before: "Much", after: ", thank you.",
    post: [],
    correct: "better", correctJa: "よくなった",
    fullJa: "きょうの ぐあいは どう、おじいちゃん? だいぶ よくなったよ、ありがとう。",
    wrongs: ["shorter", "louder", "smaller"] },
  { pre: [],
    blankSpeaker: null,
    before: "There is a big", after: "between the two tall buildings downtown.",
    post: [],
    correct: "park", correctJa: "こうえん",
    fullJa: "まちなかの たかい ビル2つの あいだに おおきな こうえんが ある。",
    wrongs: ["spoon", "pencil", "clock"] },
  { pre: [],
    blankSpeaker: "A",
    before: "Whose turn is it to", after: "the dishes tonight?",
    post: [{ speaker: "B", text: "I think it's mine." }],
    correct: "wash", correctJa: "あらう",
    fullJa: "こんばん だれが おさらを あらう ばんだっけ? わたしだと おもうよ。",
    wrongs: ["paint", "sell", "grow"] },
  { pre: [],
    blankSpeaker: "A",
    before: "I'm going to visit my uncle", after: "train this weekend.",
    post: [{ speaker: "B", text: "Have a nice trip!" }],
    correct: "by", correctJa: "でんしゃで",
    fullJa: "こんしゅうまつ でんしゃで おじさんの ところに いくんだ。楽しんできてね!",
    wrongs: ["at", "in", "for"] },
  { pre: [],
    blankSpeaker: "A",
    before: "This is a picture", after: "my family at the zoo.",
    post: [{ speaker: "B", text: "You all look so happy!" }],
    correct: "of", correctJa: "の",
    fullJa: "これは どうぶつえんでの かぞくの しゃしんなんだ。みんな すごく たのしそう!",
    wrongs: ["at", "in", "by"] },
  { pre: [],
    blankSpeaker: "A",
    before: "Can you turn", after: "the TV? It's too loud.",
    post: [{ speaker: "B", text: "Sorry, I will." }],
    correct: "down", correctJa: "小さくする",
    fullJa: "テレビの おと 小さくしてくれる? うるさいから。ごめん、そうする。",
    wrongs: ["up", "in", "at"] },
  { pre: [],
    blankSpeaker: "A",
    before: "Look! A rabbit is sitting", after: "that tree.",
    post: [{ speaker: "B", text: "Wow, it's so cute." }],
    correct: "under", correctJa: "したに",
    fullJa: "見て!うさぎが あの きの したに すわってる。わあ、かわいい。",
    wrongs: ["from", "into", "along"] },
];
