/* =========================================================
   えいごクラフト 5きゅう - dialogue-data.js

   大もん2(会話文の文空所補充)・リスニング第1部(会話の応答文選択)・
   第2部(会話の内容一致選択)の れんしゅうよう データ。

   ぜんぶ オリジナルで かいた 会話文です。ほんばんの 過去問は
   きょうかいが「複製・漏えい(ネットへの けいさいを ふくむ)を きんじる」と
   はっきり しめしているため、このアプリには 一字一句 うつしていません。
   出題の「かたち」(なんぎょうの 会話か、なんこの せんたくしか)だけを
   ほんばんに あわせ、なかみは ぜんぶ 新規に かいています。
   ========================================================= */

/* ---------- 大もん2: 会話文の文空所補充 ----------
   A の はつげんに つづく B の こたえの ( ) を うめる。
   a: A の せりふ、after: ( )の あとに つづく きまった 文(なければ "")、
   correct/correctJa: せいかいの こたえと いみ、wrongs: まちがいの こたえ3つ */
const DAIMON2_POOL = [
  { a: "Are you free this afternoon?", after: "I have piano practice.",
    correct: "No, I'm not.", correctJa: "ううん、ひまじゃないよ。",
    wrongs: ["Yes, please.", "You're welcome.", "Nice to meet you."] },
  { a: "Do you have any questions?", after: "",
    correct: "No, I don't.", correctJa: "いいえ、ありません。",
    wrongs: ["Yes, please.", "I'm eight years old.", "It's Monday."] },
  { a: "I like your new bag.", after: "",
    correct: "Thank you.", correctJa: "ありがとう。",
    wrongs: ["I'm sorry.", "Me, too.", "Not yet."] },
  { a: "Excuse me, is this seat free?", after: "",
    correct: "Yes, it is.", correctJa: "はい、あいてます。",
    wrongs: ["I don't know him.", "It's five o'clock.", "That's too bad."] },
  { a: "Let's play soccer after school.", after: "",
    correct: "Sounds good.", correctJa: "いいね。",
    wrongs: ["I'm sorry to hear that.", "You're welcome.", "See you."] },
  { a: "Can I borrow your pencil?", after: "Here you are.",
    correct: "Sure.", correctJa: "いいよ。",
    wrongs: ["No, thanks.", "I don't know.", "Not really."] },
  { a: "Did you finish your homework?", after: "",
    correct: "Not yet.", correctJa: "まだだよ。",
    wrongs: ["It's raining.", "I'm eight.", "See you tomorrow."] },
  { a: "How many pens do you have?", after: "",
    correct: "I have three.", correctJa: "3本 もってるよ。",
    wrongs: ["I like blue.", "It's on the desk.", "Yes, I do."] },
  { a: "What time is it now?", after: "",
    correct: "It's noon.", correctJa: "ちょうど お昼だよ。",
    wrongs: ["It's Friday.", "I'm fine.", "I have two."] },
  { a: "Whose bag is this?", after: "",
    correct: "It's mine.", correctJa: "わたしのだよ。",
    wrongs: ["It's blue.", "I'm ten.", "That's right."] },
  { a: "Do you want some tea?", after: "",
    correct: "Yes, please.", correctJa: "うん、ください。",
    wrongs: ["I'm sorry.", "Nice to meet you.", "That's too bad."] },
  { a: "I can't find my key.", after: "",
    correct: "That's too bad.", correctJa: "それは たいへんだね。",
    wrongs: ["Good idea.", "Congratulations.", "You're welcome."] },
  { a: "Thank you for the present.", after: "",
    correct: "You're welcome.", correctJa: "どういたしまして。",
    wrongs: ["Thank you, too.", "I'm sorry.", "Not really."] },
  { a: "I'm sorry I'm late.", after: "",
    correct: "That's OK.", correctJa: "だいじょうぶだよ。",
    wrongs: ["Me, too.", "I don't think so.", "Good job."] },
  { a: "Where do you want to go this weekend?", after: "",
    correct: "I want to go to the zoo.", correctJa: "どうぶつえんに 行きたいな。",
    wrongs: ["I have two sisters.", "It's Tuesday.", "Yes, I can."] },
  { a: "Which bag is yours, the red one or the blue one?", after: "",
    correct: "The blue one is mine.", correctJa: "青いのが わたしのだよ。",
    wrongs: ["It's under the table.", "I'm fine, thanks.", "That's right."] },
  { a: "Why are you so happy today?", after: "",
    correct: "Because it's my birthday.", correctJa: "だって たんじょうびだから。",
    wrongs: ["At six o'clock.", "Near the station.", "By bus."] },
  { a: "How do you go to school?", after: "",
    correct: "I go by bike.", correctJa: "じてんしゃで 行くよ。",
    wrongs: ["I go with Ken.", "I have three.", "Yes, it is."] },
  { a: "Is this your notebook?", after: "",
    correct: "No, it isn't.", correctJa: "ううん、ちがうよ。",
    wrongs: ["Yes, please.", "I'm sorry to hear that.", "Not yet."] },
  { a: "Happy birthday, Tom!", after: "",
    correct: "Thanks a lot.", correctJa: "ありがとう!",
    wrongs: ["Me, too.", "Not at all.", "See you."] },
  { a: "Do you often watch TV at night?", after: "",
    correct: "No, I usually read books.", correctJa: "ううん、たいてい 本を よむよ。",
    wrongs: ["It's white.", "I'm nine.", "By train."] },
  { a: "Can you close the window, please?", after: "",
    correct: "Sure, Mom.", correctJa: "いいよ、おかあさん。",
    wrongs: ["I like it.", "That's right.", "See you soon."] },
  { a: "Is your father a teacher?", after: "",
    correct: "No, he's a doctor.", correctJa: "ううん、おいしゃさんだよ。",
    wrongs: ["Yes, please.", "It's cloudy.", "I have one."] },
  { a: "Nice to meet you.", after: "",
    correct: "Nice to meet you, too.", correctJa: "こちらこそ、はじめまして。",
    wrongs: ["You're welcome.", "That's too bad.", "I'm sorry."] },
];

/* ---------- リスニング第1部: 会話の応答文選択 ----------
   1つの はつげんを きいて、いちばん あう こたえを 3つから えらぶ。
   えいごの もじは 出さない(きくだけで こたえる)。 */
const LISTEN1_POOL = [
  { prompt: "How are you today?", promptJa: "きょうの ちょうしは どう?",
    correct: "I'm fine, thank you.", correctJa: "げんきだよ、ありがとう。",
    wrongs: ["It's five o'clock.", "I have two dogs."] },
  { prompt: "What's your name?", promptJa: "なまえは なに?",
    correct: "My name is Emma.", correctJa: "わたしは エマだよ。",
    wrongs: ["I'm ten years old.", "It's on the table."] },
  { prompt: "Do you like apples?", promptJa: "りんご すき?",
    correct: "Yes, I do.", correctJa: "うん、すきだよ。",
    wrongs: ["I'm from Japan.", "It's Monday."] },
  { prompt: "See you tomorrow!", promptJa: "また あした!",
    correct: "See you!", correctJa: "またね!",
    wrongs: ["Nice to meet you.", "I'm sorry."] },
  { prompt: "Can you help me, please?", promptJa: "てつだって くれる?",
    correct: "Sure, no problem.", correctJa: "うん、いいよ。",
    wrongs: ["That's too bad.", "Happy birthday."] },
  { prompt: "Where is the library?", promptJa: "としょかんは どこ?",
    correct: "It's near the park.", correctJa: "こうえんの ちかくだよ。",
    wrongs: ["I'm fine, thanks.", "At seven o'clock."] },
  { prompt: "How old are you?", promptJa: "なんさい?",
    correct: "I'm nine.", correctJa: "9さいだよ。",
    wrongs: ["I'm from Canada.", "It's rainy."] },
  { prompt: "Whose umbrella is this?", promptJa: "これ だれの かさ?",
    correct: "It's mine.", correctJa: "わたしのだよ。",
    wrongs: ["It's red.", "At the door."] },
  { prompt: "What time do you get up?", promptJa: "なんじに おきるの?",
    correct: "I get up at seven.", correctJa: "7じに おきるよ。",
    wrongs: ["I like milk.", "It's my bag."] },
  { prompt: "Thank you very much.", promptJa: "どうも ありがとう。",
    correct: "You're welcome.", correctJa: "どういたしまして。",
    wrongs: ["I'm sorry.", "Not yet."] },
  { prompt: "Is it raining outside?", promptJa: "そと あめ ふってる?",
    correct: "Yes, it is.", correctJa: "うん、ふってるよ。",
    wrongs: ["I'm eight.", "It's blue."] },
  { prompt: "What do you want for lunch?", promptJa: "おひるごはんは なにが いい?",
    correct: "I want pizza.", correctJa: "ピザが いいな。",
    wrongs: ["I'm at school.", "On Sunday."] },
  { prompt: "Let's go to the park.", promptJa: "こうえんに いこう。",
    correct: "OK, let's go.", correctJa: "うん、いこう。",
    wrongs: ["I'm sorry to hear that.", "You're welcome."] },
  { prompt: "How many brothers do you have?", promptJa: "おとうと・おにいさんは なんにん?",
    correct: "I have one brother.", correctJa: "ひとり いるよ。",
    wrongs: ["I like soccer.", "It's cold today."] },
  { prompt: "Where are you from?", promptJa: "出身は どこ?",
    correct: "I'm from Osaka.", correctJa: "おおさか出身だよ。",
    wrongs: ["It's three o'clock.", "I have a cat."] },
  { prompt: "Is your sister a student?", promptJa: "おねえさんは 学生?",
    correct: "Yes, she is.", correctJa: "うん、そうだよ。",
    wrongs: ["It's sunny.", "I'm ten."] },
  { prompt: "What's the weather like today?", promptJa: "きょうの てんきは?",
    correct: "It's cloudy.", correctJa: "くもりだよ。",
    wrongs: ["I'm fine.", "At the station."] },
  { prompt: "Do you play the piano?", promptJa: "ピアノ ひく?",
    correct: "Yes, every day.", correctJa: "うん、まいにち ひくよ。",
    wrongs: ["It's my pen.", "I'm from Kyoto."] },
  { prompt: "Sorry, I'm late.", promptJa: "ごめん、おくれた。",
    correct: "That's OK.", correctJa: "だいじょうぶだよ。",
    wrongs: ["Good idea.", "Congratulations."] },
  { prompt: "What day is it today?", promptJa: "きょうは 何曜日?",
    correct: "It's Wednesday.", correctJa: "水曜日だよ。",
    wrongs: ["It's nine o'clock.", "I'm happy."] },
  { prompt: "Can I use your phone?", promptJa: "でんわ かりても いい?",
    correct: "Sorry, I don't have one.", correctJa: "ごめん、もってないんだ。",
    wrongs: ["Yes, I can.", "It's Friday."] },
  { prompt: "How do you come to school?", promptJa: "がっこうまで どうやって くるの?",
    correct: "I walk to school.", correctJa: "あるいて くるよ。",
    wrongs: ["I have two pens.", "It's my book."] },
  { prompt: "Do you have any pets?", promptJa: "ペット かってる?",
    correct: "Yes, I have a dog.", correctJa: "うん、いぬを かってるよ。",
    wrongs: ["I'm in the kitchen.", "It's four o'clock."] },
  { prompt: "Nice to meet you.", promptJa: "はじめまして。",
    correct: "Nice to meet you, too.", correctJa: "こちらこそ、はじめまして。",
    wrongs: ["Good night.", "You're welcome."] },
];

/* ---------- リスニング第2部: 会話の内容一致選択 ----------
   2ぎょうの 会話 + しつもんを きいて、ないように あう こたえを
   4つの もじの せんたくしから えらぶ(せんたくしだけは 見える)。 */
const LISTEN2_POOL = [
  { a: "Ken, what do you have for breakfast?", b: "I have rice and eggs, Mom.",
    q: "What does Ken have for breakfast?", qJa: "ケンは 朝ごはんに なにを 食べる?",
    correct: "Rice and eggs.",
    wrongs: ["Bread and milk.", "Soup and salad.", "Fish and rice balls."] },
  { a: "Do you want to go to the zoo or the museum, Emma?", b: "I want to go to the zoo.",
    q: "Where does Emma want to go?", qJa: "エマは どこに 行きたい?",
    correct: "To the zoo.",
    wrongs: ["To the museum.", "To the park.", "To the library."] },
  { a: "Mike, how many cats do you have?", b: "I have two cats and one dog.",
    q: "How many cats does Mike have?", qJa: "マイクは ねこを 何びき かってる?",
    correct: "Two.",
    wrongs: ["One.", "Three.", "None."] },
  { a: "Lisa, what time does your class start?", b: "It starts at nine o'clock.",
    q: "What time does Lisa's class start?", qJa: "リサの じゅぎょうは 何じから?",
    correct: "At nine o'clock.",
    wrongs: ["At eight o'clock.", "At ten o'clock.", "At noon."] },
  { a: "Tom, is your father a doctor?", b: "No, he's a teacher.",
    q: "What is Tom's father?", qJa: "トムの おとうさんの しごとは?",
    correct: "A teacher.",
    wrongs: ["A doctor.", "A nurse.", "A student."] },
  { a: "Kate, what's your favorite sport?", b: "I like tennis the best.",
    q: "What is Kate's favorite sport?", qJa: "ケイトが いちばん すきな スポーツは?",
    correct: "Tennis.",
    wrongs: ["Soccer.", "Baseball.", "Swimming."] },
  { a: "Jack, where is your bag?", b: "It's under the chair.",
    q: "Where is Jack's bag?", qJa: "ジャックの かばんは どこ?",
    correct: "Under the chair.",
    wrongs: ["On the chair.", "Under the table.", "In the box."] },
  { a: "Amy, whose pencil case is this?", b: "It's my brother's.",
    q: "Whose pencil case is it?", qJa: "だれの ふでばこ?",
    correct: "Amy's brother's.",
    wrongs: ["Amy's.", "Amy's sister's.", "Amy's teacher's."] },
  { a: "Sam, how do you go to the station?", b: "I usually go by bus.",
    q: "How does Sam usually go to the station?", qJa: "サムは どうやって えきに 行く?",
    correct: "By bus.",
    wrongs: ["By bike.", "By train.", "On foot."] },
  { a: "Ben, do you often play video games?", b: "Yes, I play them every weekend.",
    q: "When does Ben play video games?", qJa: "ベンは いつ ゲームを する?",
    correct: "Every weekend.",
    wrongs: ["Every morning.", "Every day.", "Every Monday."] },
  { a: "Nancy, what color is your new bike?", b: "It's yellow.",
    q: "What color is Nancy's new bike?", qJa: "ナンシーの あたらしい じてんしゃの 色は?",
    correct: "Yellow.",
    wrongs: ["Blue.", "Red.", "Green."] },
  { a: "Paul, how old is your grandmother?", b: "She is sixty-five.",
    q: "How old is Paul's grandmother?", qJa: "ポールの おばあさんは 何さい?",
    correct: "Sixty-five.",
    wrongs: ["Fifty-five.", "Seventy-five.", "Forty-five."] },
  { a: "Sara, what do you usually drink in the morning?", b: "I usually drink orange juice.",
    q: "What does Sara usually drink in the morning?", qJa: "サラは 朝 いつも なにを のむ?",
    correct: "Orange juice.",
    wrongs: ["Milk.", "Tea.", "Water."] },
  { a: "Alex, which season do you like the best?", b: "I like winter the best.",
    q: "Which season does Alex like the best?", qJa: "アレックスが いちばん すきな きせつは?",
    correct: "Winter.",
    wrongs: ["Summer.", "Spring.", "Fall."] },
  { a: "Emily, where do you study every night?", b: "I study in my room.",
    q: "Where does Emily study every night?", qJa: "エミリーは まいばん どこで べんきょうする?",
    correct: "In her room.",
    wrongs: ["In the kitchen.", "In the living room.", "At the library."] },
  { a: "David, what day do you have music class?", b: "I have it on Thursday.",
    q: "What day does David have music class?", qJa: "デイビッドの おんがくの じゅぎょうは 何曜日?",
    correct: "Thursday.",
    wrongs: ["Tuesday.", "Wednesday.", "Friday."] },
  { a: "Olivia, how many books do you read every month?", b: "I read about four books.",
    q: "How many books does Olivia read every month?", qJa: "オリビアは 1か月に 何さつ 本を よむ?",
    correct: "About four.",
    wrongs: ["About two.", "About six.", "About eight."] },
  { a: "Kevin, who is your best friend?", b: "Jim is my best friend.",
    q: "Who is Kevin's best friend?", qJa: "ケビンの いちばんの ともだちは だれ?",
    correct: "Jim.",
    wrongs: ["Tom.", "Ben.", "Sam."] },
  { a: "Hana, what is your mother's job?", b: "She is a nurse.",
    q: "What is Hana's mother's job?", qJa: "ハナの おかあさんの しごとは?",
    correct: "A nurse.",
    wrongs: ["A teacher.", "A doctor.", "A cook."] },
  { a: "Leo, when is your birthday?", b: "It's in May.",
    q: "When is Leo's birthday?", qJa: "レオの たんじょうびは いつ?",
    correct: "In May.",
    wrongs: ["In April.", "In June.", "In March."] },
];
