/*
 * えいけん5きゅう たんごデータ
 * カテゴリごとに ならべてあります。10こずつ「ゾーン」に わけられます(app.js側で自動計算)。
 */
const WORD_LIST = [
  // ===== すうじ =====
  { en: "one", ja: "1(いち)", emoji: "1️⃣", ex: "I have one apple.", exJa: "わたしは りんごを 1つ もっています。" },
  { en: "two", ja: "2(に)", emoji: "2️⃣", ex: "I have two dogs.", exJa: "わたしは いぬを 2ひき かっています。" },
  { en: "three", ja: "3(さん)", emoji: "3️⃣", ex: "I have three pens.", exJa: "わたしは ペンを 3ぼん もっています。" },
  { en: "four", ja: "4(よん)", emoji: "4️⃣", ex: "I am four years old.", exJa: "わたしは 4さいです。" },
  { en: "five", ja: "5(ご)", emoji: "5️⃣", ex: "I have five balls.", exJa: "わたしは ボールを 5つ もっています。" },
  { en: "six", ja: "6(ろく)", emoji: "6️⃣", ex: "It is six o'clock.", exJa: "6じです。" },
  { en: "seven", ja: "7(なな)", emoji: "7️⃣", ex: "I have seven books.", exJa: "わたしは 本を 7さつ もっています。" },
  { en: "eight", ja: "8(はち)", emoji: "8️⃣", ex: "I am eight years old.", exJa: "わたしは 8さいです。" },
  { en: "nine", ja: "9(きゅう)", emoji: "9️⃣", ex: "It is nine o'clock.", exJa: "9じです。" },
  { en: "ten", ja: "10(じゅう)", emoji: "🔟", ex: "I have ten fingers.", exJa: "わたしは ゆびが 10ぽん あります。" },
  { en: "eleven", ja: "11(じゅういち)", emoji: "🔢", ex: "I am eleven years old.", exJa: "わたしは 11さいです。" },
  { en: "twelve", ja: "12(じゅうに)", emoji: "🔢", ex: "There are twelve months.", exJa: "1ねんは 12かげつです。" },
  { en: "thirteen", ja: "13(じゅうさん)", emoji: "🔢", ex: "I am thirteen.", exJa: "わたしは 13さいです。" },
  { en: "fourteen", ja: "14(じゅうよん)", emoji: "🔢", ex: "I have fourteen pencils.", exJa: "えんぴつを 14ほん もっています。" },
  { en: "fifteen", ja: "15(じゅうご)", emoji: "🔢", ex: "It is fifteen minutes.", exJa: "15ふんです。" },
  { en: "sixteen", ja: "16(じゅうろく)", emoji: "🔢", ex: "I have sixteen cards.", exJa: "カードを 16まい もっています。" },
  { en: "seventeen", ja: "17(じゅうなな)", emoji: "🔢", ex: "There are seventeen students.", exJa: "せいとが 17にん います。" },
  { en: "eighteen", ja: "18(じゅうはち)", emoji: "🔢", ex: "I am eighteen.", exJa: "わたしは 18さいです。" },
  { en: "nineteen", ja: "19(じゅうきゅう)", emoji: "🔢", ex: "It is nineteen dollars.", exJa: "19ドルです。" },
  { en: "twenty", ja: "20(にじゅう)", emoji: "🔢", ex: "I have twenty stickers.", exJa: "シールを 20まい もっています。" },
  { en: "thirty", ja: "30(さんじゅう)", emoji: "🔢", ex: "It is thirty minutes.", exJa: "30ぷんです。" },
  { en: "forty", ja: "40(よんじゅう)", emoji: "🔢", ex: "There are forty people.", exJa: "40にん います。" },
  { en: "fifty", ja: "50(ごじゅう)", emoji: "🔢", ex: "It is fifty yen.", exJa: "50えんです。" },
  { en: "sixty", ja: "60(ろくじゅう)", emoji: "🔢", ex: "There are sixty minutes in an hour.", exJa: "1じかんは 60ぷんです。" },
  { en: "hundred", ja: "100(ひゃく)", emoji: "💯", ex: "I have one hundred yen.", exJa: "100えん もっています。" },

  // ===== いろ =====
  { en: "red", ja: "あか", emoji: "🔴", ex: "I like red.", exJa: "わたしは あかが すきです。" },
  { en: "blue", ja: "あお", emoji: "🔵", ex: "The sky is blue.", exJa: "そらは あおいです。" },
  { en: "yellow", ja: "きいろ", emoji: "🟡", ex: "The banana is yellow.", exJa: "バナナは きいろです。" },
  { en: "green", ja: "みどり", emoji: "🟢", ex: "I like green.", exJa: "わたしは みどりが すきです。" },
  { en: "white", ja: "しろ", emoji: "⚪", ex: "The cat is white.", exJa: "ねこは しろいです。" },
  { en: "black", ja: "くろ", emoji: "⚫", ex: "I have a black bag.", exJa: "くろい かばんを もっています。" },
  { en: "pink", ja: "ピンク", emoji: "🩷", ex: "I like pink.", exJa: "わたしは ピンクが すきです。" },
  { en: "orange", ja: "オレンジいろ", emoji: "🟠", ex: "I like orange.", exJa: "わたしは オレンジいろが すきです。" },
  { en: "purple", ja: "むらさき", emoji: "🟣", ex: "I like purple.", exJa: "わたしは むらさきが すきです。" },
  { en: "brown", ja: "ちゃいろ", emoji: "🟤", ex: "The dog is brown.", exJa: "いぬは ちゃいろです。" },

  // ===== かぞく =====
  { en: "family", ja: "かぞく", emoji: "👨‍👩‍👧‍👦", ex: "I love my family.", exJa: "わたしは かぞくが だいすきです。" },
  { en: "father", ja: "おとうさん", emoji: "👨", ex: "My father is a teacher.", exJa: "わたしの おとうさんは 先生せんせいです。" },
  { en: "mother", ja: "おかあさん", emoji: "👩", ex: "My mother is kind.", exJa: "わたしの おかあさんは やさしいです。" },
  { en: "brother", ja: "きょうだい(おとこ)", emoji: "👦", ex: "I have a brother.", exJa: "わたしには きょうだいが います。" },
  { en: "sister", ja: "きょうだい(おんな)", emoji: "👧", ex: "I have a sister.", exJa: "わたしには きょうだいが います。" },
  { en: "grandfather", ja: "おじいさん", emoji: "👴", ex: "My grandfather is 70.", exJa: "わたしの おじいさんは 70さいです。" },
  { en: "grandmother", ja: "おばあさん", emoji: "👵", ex: "My grandmother is kind.", exJa: "わたしの おばあさんは やさしいです。" },
  { en: "aunt", ja: "おばさん", emoji: "👩‍🦰", ex: "My aunt is a doctor.", exJa: "わたしの おばさんは いしゃです。" },
  { en: "uncle", ja: "おじさん", emoji: "👨‍🦰", ex: "My uncle is tall.", exJa: "わたしの おじさんは せが たかいです。" },
  { en: "baby", ja: "あかちゃん", emoji: "👶", ex: "The baby is cute.", exJa: "あかちゃんは かわいいです。" },

  // ===== からだ =====
  { en: "head", ja: "あたま", emoji: "🧠", ex: "My head hurts.", exJa: "あたまが いたいです。" },
  { en: "face", ja: "かお", emoji: "😀", ex: "Wash your face.", exJa: "かおを あらいなさい。" },
  { en: "eye", ja: "め", emoji: "👁️", ex: "I have big eyes.", exJa: "わたしは めが おおきいです。" },
  { en: "ear", ja: "みみ", emoji: "👂", ex: "The rabbit has long ears.", exJa: "うさぎは みみが ながいです。" },
  { en: "nose", ja: "はな", emoji: "👃", ex: "My nose is small.", exJa: "わたしの はなは ちいさいです。" },
  { en: "mouth", ja: "くち", emoji: "👄", ex: "Open your mouth.", exJa: "くちを あけなさい。" },
  { en: "hand", ja: "て", emoji: "✋", ex: "Wash your hands.", exJa: "てを あらいなさい。" },
  { en: "foot", ja: "あし(足首から下)", emoji: "🦶", ex: "My foot is big.", exJa: "わたしの あしは おおきいです。" },
  { en: "hair", ja: "かみのけ", emoji: "💇", ex: "She has long hair.", exJa: "かのじょは かみが ながいです。" },
  { en: "arm", ja: "うで", emoji: "💪", ex: "I have strong arms.", exJa: "わたしは うでが つよいです。" },

  // ===== どうぶつ =====
  { en: "dog", ja: "いぬ", emoji: "🐶", ex: "I have a dog.", exJa: "わたしは いぬを かっています。" },
  { en: "cat", ja: "ねこ", emoji: "🐱", ex: "I like cats.", exJa: "わたしは ねこが すきです。" },
  { en: "bird", ja: "とり", emoji: "🐦", ex: "The bird can sing.", exJa: "とりは うたえます。" },
  { en: "fish", ja: "さかな", emoji: "🐟", ex: "Fish can swim.", exJa: "さかなは およげます。" },
  { en: "rabbit", ja: "うさぎ", emoji: "🐰", ex: "The rabbit is fast.", exJa: "うさぎは はやいです。" },
  { en: "horse", ja: "うま", emoji: "🐴", ex: "I like horses.", exJa: "わたしは うまが すきです。" },
  { en: "cow", ja: "うし", emoji: "🐮", ex: "The cow is big.", exJa: "うしは おおきいです。" },
  { en: "pig", ja: "ぶた", emoji: "🐷", ex: "The pig is pink.", exJa: "ぶたは ピンクいろです。" },
  { en: "lion", ja: "ライオン", emoji: "🦁", ex: "The lion is strong.", exJa: "ライオンは つよいです。" },
  { en: "tiger", ja: "とら", emoji: "🐯", ex: "I saw a tiger.", exJa: "とらを 見みました。" },
  { en: "elephant", ja: "ぞう", emoji: "🐘", ex: "The elephant is big.", exJa: "ぞうは おおきいです。" },
  { en: "monkey", ja: "さる", emoji: "🐵", ex: "The monkey is funny.", exJa: "さるは おもしろいです。" },
  { en: "bear", ja: "くま", emoji: "🐻", ex: "I like the panda bear.", exJa: "わたしは パンダが すきです。" },
  { en: "panda", ja: "パンダ", emoji: "🐼", ex: "The panda is cute.", exJa: "パンダは かわいいです。" },
  { en: "mouse", ja: "ねずみ", emoji: "🐭", ex: "The mouse is small.", exJa: "ねずみは ちいさいです。" },
  { en: "duck", ja: "あひる", emoji: "🦆", ex: "The duck can swim.", exJa: "あひるは およげます。" },
  { en: "frog", ja: "かえる", emoji: "🐸", ex: "The frog can jump.", exJa: "かえるは ジャンプできます。" },
  { en: "sheep", ja: "ひつじ", emoji: "🐑", ex: "I see sheep.", exJa: "ひつじが 見みえます。" },
  { en: "chicken", ja: "にわとり", emoji: "🐔", ex: "The chicken is on the farm.", exJa: "にわとりは のうじょうに います。" },
  { en: "snake", ja: "へび", emoji: "🐍", ex: "The snake is long.", exJa: "へびは ながいです。" },

  // ===== たべもの・のみもの =====
  { en: "apple", ja: "りんご", emoji: "🍎", ex: "I like apples.", exJa: "わたしは りんごが すきです。" },
  { en: "banana", ja: "バナナ", emoji: "🍌", ex: "I eat a banana.", exJa: "わたしは バナナを たべます。" },
  { en: "orange", ja: "オレンジ", emoji: "🍊", ex: "I like oranges.", exJa: "わたしは オレンジが すきです。" },
  { en: "strawberry", ja: "いちご", emoji: "🍓", ex: "I like strawberries.", exJa: "わたしは いちごが すきです。" },
  { en: "melon", ja: "メロン", emoji: "🍈", ex: "The melon is sweet.", exJa: "メロンは あまいです。" },
  { en: "grape", ja: "ぶどう", emoji: "🍇", ex: "I like grapes.", exJa: "わたしは ぶどうが すきです。" },
  { en: "rice", ja: "ごはん", emoji: "🍚", ex: "I eat rice every day.", exJa: "まいにち ごはんを たべます。" },
  { en: "bread", ja: "パン", emoji: "🍞", ex: "I eat bread.", exJa: "わたしは パンを たべます。" },
  { en: "egg", ja: "たまご", emoji: "🥚", ex: "I like eggs.", exJa: "わたしは たまごが すきです。" },
  { en: "milk", ja: "ぎゅうにゅう", emoji: "🥛", ex: "I drink milk.", exJa: "わたしは ぎゅうにゅうを のみます。" },
  { en: "water", ja: "みず", emoji: "💧", ex: "I drink water.", exJa: "わたしは みずを のみます。" },
  { en: "juice", ja: "ジュース", emoji: "🧃", ex: "I like orange juice.", exJa: "わたしは オレンジジュースが すきです。" },
  { en: "tea", ja: "おちゃ", emoji: "🍵", ex: "I drink tea.", exJa: "わたしは おちゃを のみます。" },
  { en: "cake", ja: "ケーキ", emoji: "🍰", ex: "I like cake.", exJa: "わたしは ケーキが すきです。" },
  { en: "cookie", ja: "クッキー", emoji: "🍪", ex: "I eat a cookie.", exJa: "わたしは クッキーを たべます。" },
  { en: "candy", ja: "あめ", emoji: "🍬", ex: "I like candy.", exJa: "わたしは あめが すきです。" },
  { en: "ice cream", ja: "アイスクリーム", emoji: "🍦", ex: "I like ice cream.", exJa: "わたしは アイスクリームが すきです。" },
  { en: "pizza", ja: "ピザ", emoji: "🍕", ex: "I like pizza.", exJa: "わたしは ピザが すきです。" },
  { en: "hamburger", ja: "ハンバーガー", emoji: "🍔", ex: "I eat a hamburger.", exJa: "わたしは ハンバーガーを たべます。" },
  { en: "salad", ja: "サラダ", emoji: "🥗", ex: "I eat salad.", exJa: "わたしは サラダを たべます。" },
  { en: "soup", ja: "スープ", emoji: "🍲", ex: "The soup is hot.", exJa: "スープは あついです。" },
  { en: "meat", ja: "にく", emoji: "🍖", ex: "I like meat.", exJa: "わたしは にくが すきです。" },
  { en: "vegetable", ja: "やさい", emoji: "🥦", ex: "Eat your vegetables.", exJa: "やさいを たべなさい。" },
  { en: "fruit", ja: "くだもの", emoji: "🍉", ex: "I like fruit.", exJa: "わたしは くだものが すきです。" },
  { en: "lunch", ja: "ひるごはん", emoji: "🍱", ex: "I eat lunch at noon.", exJa: "しょうごに ひるごはんを たべます。" },
  { en: "breakfast", ja: "あさごはん", emoji: "🥞", ex: "I eat breakfast.", exJa: "わたしは あさごはんを たべます。" },
  { en: "dinner", ja: "ばんごはん", emoji: "🍽️", ex: "We eat dinner together.", exJa: "いっしょに ばんごはんを たべます。" },

  // ===== がっこう =====
  { en: "school", ja: "がっこう", emoji: "🏫", ex: "I go to school.", exJa: "わたしは がっこうへ いきます。" },
  { en: "classroom", ja: "きょうしつ", emoji: "🚪", ex: "This is my classroom.", exJa: "これは わたしの きょうしつです。" },
  { en: "teacher", ja: "先生せんせい", emoji: "🧑‍🏫", ex: "My teacher is kind.", exJa: "わたしの 先生せんせいは やさしいです。" },
  { en: "student", ja: "せいと", emoji: "🧑‍🎓", ex: "I am a student.", exJa: "わたしは せいとです。" },
  { en: "friend", ja: "ともだち", emoji: "🧑‍🤝‍🧑", ex: "He is my friend.", exJa: "かれは わたしの ともだちです。" },
  { en: "book", ja: "ほん", emoji: "📖", ex: "I like this book.", exJa: "わたしは この本ほんが すきです。" },
  { en: "notebook", ja: "ノート", emoji: "📓", ex: "I write in my notebook.", exJa: "ノートに かきます。" },
  { en: "pencil", ja: "えんぴつ", emoji: "✏️", ex: "I use a pencil.", exJa: "えんぴつを つかいます。" },
  { en: "pen", ja: "ペン", emoji: "🖊️", ex: "I have a red pen.", exJa: "あかい ペンを もっています。" },
  { en: "eraser", ja: "けしごむ", emoji: "🧼", ex: "I need an eraser.", exJa: "けしごむが ひつようです。" },
  { en: "ruler", ja: "じょうぎ", emoji: "📏", ex: "I use a ruler.", exJa: "じょうぎを つかいます。" },
  { en: "bag", ja: "かばん", emoji: "🎒", ex: "This is my bag.", exJa: "これは わたしの かばんです。" },
  { en: "desk", ja: "つくえ", emoji: "🪑", ex: "My desk is clean.", exJa: "わたしの つくえは きれいです。" },
  { en: "homework", ja: "しゅくだい", emoji: "📝", ex: "I do my homework.", exJa: "わたしは しゅくだいを します。" },
  { en: "test", ja: "テスト", emoji: "📋", ex: "I have a test today.", exJa: "きょう テストが あります。" },
  { en: "English", ja: "えいご", emoji: "🇬🇧", ex: "I study English.", exJa: "わたしは えいごを べんきょうします。" },
  { en: "math", ja: "さんすう", emoji: "🔢", ex: "I like math.", exJa: "わたしは さんすうが すきです。" },
  { en: "music", ja: "おんがく", emoji: "🎵", ex: "I like music class.", exJa: "わたしは おんがくの じかんが すきです。" },
  { en: "art", ja: "ずこう", emoji: "🎨", ex: "I like art class.", exJa: "わたしは ずこうが すきです。" },
  { en: "library", ja: "としょかん", emoji: "📚", ex: "I go to the library.", exJa: "わたしは としょかんへ いきます。" },

  // ===== スポーツ・あそび =====
  { en: "soccer", ja: "サッカー", emoji: "⚽", ex: "I play soccer.", exJa: "わたしは サッカーを します。" },
  { en: "baseball", ja: "やきゅう", emoji: "⚾", ex: "I like baseball.", exJa: "わたしは やきゅうが すきです。" },
  { en: "basketball", ja: "バスケットボール", emoji: "🏀", ex: "I play basketball.", exJa: "わたしは バスケットボールを します。" },
  { en: "tennis", ja: "テニス", emoji: "🎾", ex: "I play tennis.", exJa: "わたしは テニスを します。" },
  { en: "swimming", ja: "すいえい", emoji: "🏊", ex: "I like swimming.", exJa: "わたしは すいえいが すきです。" },
  { en: "volleyball", ja: "バレーボール", emoji: "🏐", ex: "I play volleyball.", exJa: "わたしは バレーボールを します。" },
  { en: "game", ja: "ゲーム", emoji: "🎮", ex: "I like video games.", exJa: "わたしは ゲームが すきです。" },
  { en: "ball", ja: "ボール", emoji: "🏐", ex: "Throw the ball.", exJa: "ボールを なげて。" },
  { en: "bike", ja: "じてんしゃ", emoji: "🚲", ex: "I ride my bike.", exJa: "わたしは じてんしゃに のります。" },
  { en: "park", ja: "こうえん", emoji: "🏞️", ex: "I play in the park.", exJa: "わたしは こうえんで あそびます。" },
  { en: "piano", ja: "ピアノ", emoji: "🎹", ex: "I can play the piano.", exJa: "わたしは ピアノが ひけます。" },
  { en: "guitar", ja: "ギター", emoji: "🎸", ex: "I can play the guitar.", exJa: "わたしは ギターが ひけます。" },

  // ===== しょくぎょう =====
  { en: "doctor", ja: "いしゃ", emoji: "🧑‍⚕️", ex: "My mother is a doctor.", exJa: "わたしの おかあさんは いしゃです。" },
  { en: "nurse", ja: "かんごし", emoji: "🧑‍⚕️", ex: "She is a nurse.", exJa: "かのじょは かんごしです。" },
  { en: "police officer", ja: "けいさつかん", emoji: "👮", ex: "He is a police officer.", exJa: "かれは けいさつかんです。" },
  { en: "firefighter", ja: "しょうぼうし", emoji: "🧑‍🚒", ex: "He is a firefighter.", exJa: "かれは しょうぼうしです。" },
  { en: "cook", ja: "りょうりにん", emoji: "🧑‍🍳", ex: "My father is a cook.", exJa: "わたしの おとうさんは りょうりにんです。" },
  { en: "singer", ja: "かしゅ", emoji: "🎤", ex: "She is a famous singer.", exJa: "かのじょは ゆうめいな かしゅです。" },
  { en: "farmer", ja: "のうか", emoji: "🧑‍🌾", ex: "He is a farmer.", exJa: "かれは のうかです。" },
  { en: "pilot", ja: "パイロット", emoji: "🧑‍✈️", ex: "I want to be a pilot.", exJa: "わたしは パイロットに なりたいです。" },
  { en: "vet", ja: "じゅうい", emoji: "🐾", ex: "I want to be a vet.", exJa: "わたしは じゅういに なりたいです。" },
  { en: "astronaut", ja: "うちゅうひこうし", emoji: "🧑‍🚀", ex: "I want to be an astronaut.", exJa: "わたしは うちゅうひこうしに なりたいです。" },

  // ===== ばしょ =====
  { en: "house", ja: "いえ", emoji: "🏠", ex: "This is my house.", exJa: "これは わたしの いえです。" },
  { en: "room", ja: "へや", emoji: "🚪", ex: "This is my room.", exJa: "これは わたしの へやです。" },
  { en: "station", ja: "えき", emoji: "🚉", ex: "I go to the station.", exJa: "わたしは えきへ いきます。" },
  { en: "hospital", ja: "びょういん", emoji: "🏥", ex: "I go to the hospital.", exJa: "わたしは びょういんへ いきます。" },
  { en: "restaurant", ja: "レストラン", emoji: "🍴", ex: "We eat at a restaurant.", exJa: "レストランで たべます。" },
  { en: "zoo", ja: "どうぶつえん", emoji: "🦓", ex: "I go to the zoo.", exJa: "わたしは どうぶつえんへ いきます。" },
  { en: "museum", ja: "はくぶつかん", emoji: "🏛️", ex: "I go to the museum.", exJa: "わたしは はくぶつかんへ いきます。" },
  { en: "garden", ja: "にわ", emoji: "🌷", ex: "I like the garden.", exJa: "わたしは にわが すきです。" },
  { en: "kitchen", ja: "だいどころ", emoji: "🍳", ex: "My mother is in the kitchen.", exJa: "おかあさんは だいどころに います。" },
  { en: "store", ja: "みせ", emoji: "🏪", ex: "I go to the store.", exJa: "わたしは みせへ いきます。" },
  { en: "supermarket", ja: "スーパー", emoji: "🛒", ex: "I go to the supermarket.", exJa: "わたしは スーパーへ いきます。" },
  { en: "city", ja: "まち", emoji: "🏙️", ex: "I live in a big city.", exJa: "わたしは おおきい まちに すんでいます。" },

  // ===== のりもの =====
  { en: "car", ja: "くるま", emoji: "🚗", ex: "I like this car.", exJa: "わたしは この くるまが すきです。" },
  { en: "bus", ja: "バス", emoji: "🚌", ex: "I go by bus.", exJa: "わたしは バスで いきます。" },
  { en: "train", ja: "でんしゃ", emoji: "🚃", ex: "I go by train.", exJa: "わたしは でんしゃで いきます。" },
  { en: "plane", ja: "ひこうき", emoji: "✈️", ex: "I like planes.", exJa: "わたしは ひこうきが すきです。" },
  { en: "ship", ja: "ふね", emoji: "🚢", ex: "I see a ship.", exJa: "ふねが 見みえます。" },
  { en: "taxi", ja: "タクシー", emoji: "🚕", ex: "We take a taxi.", exJa: "タクシーに のります。" },

  // ===== てんき・きせつ =====
  { en: "sunny", ja: "はれ", emoji: "☀️", ex: "It is sunny today.", exJa: "きょうは はれです。" },
  { en: "rainy", ja: "あめ", emoji: "🌧️", ex: "It is rainy today.", exJa: "きょうは あめです。" },
  { en: "cloudy", ja: "くもり", emoji: "☁️", ex: "It is cloudy today.", exJa: "きょうは くもりです。" },
  { en: "snowy", ja: "ゆき", emoji: "❄️", ex: "It is snowy today.", exJa: "きょうは ゆきです。" },
  { en: "windy", ja: "かぜが つよい", emoji: "🌬️", ex: "It is windy today.", exJa: "きょうは かぜが つよいです。" },
  { en: "spring", ja: "はる", emoji: "🌸", ex: "I like spring.", exJa: "わたしは はるが すきです。" },
  { en: "summer", ja: "なつ", emoji: "🌻", ex: "I like summer.", exJa: "わたしは なつが すきです。" },
  { en: "fall", ja: "あき", emoji: "🍁", ex: "I like fall.", exJa: "わたしは あきが すきです。" },
  { en: "winter", ja: "ふゆ", emoji: "⛄", ex: "I like winter.", exJa: "わたしは ふゆが すきです。" },

  // ===== ようび・つき =====
  { en: "Sunday", ja: "にちようび", emoji: "📅", ex: "Today is Sunday.", exJa: "きょうは にちようびです。" },
  { en: "Monday", ja: "げつようび", emoji: "📅", ex: "Today is Monday.", exJa: "きょうは げつようびです。" },
  { en: "Tuesday", ja: "かようび", emoji: "📅", ex: "Today is Tuesday.", exJa: "きょうは かようびです。" },
  { en: "Wednesday", ja: "すいようび", emoji: "📅", ex: "Today is Wednesday.", exJa: "きょうは すいようびです。" },
  { en: "Thursday", ja: "もくようび", emoji: "📅", ex: "Today is Thursday.", exJa: "きょうは もくようびです。" },
  { en: "Friday", ja: "きんようび", emoji: "📅", ex: "Today is Friday.", exJa: "きょうは きんようびです。" },
  { en: "Saturday", ja: "どようび", emoji: "📅", ex: "Today is Saturday.", exJa: "きょうは どようびです。" },
  { en: "January", ja: "1がつ", emoji: "🗓️", ex: "My birthday is in January.", exJa: "わたしの たんじょうびは 1がつです。" },
  { en: "April", ja: "4がつ", emoji: "🗓️", ex: "School starts in April.", exJa: "がっこうは 4がつに はじまります。" },
  { en: "October", ja: "10がつ", emoji: "🗓️", ex: "The test is in October.", exJa: "テストは 10がつです。" },
  { en: "December", ja: "12がつ", emoji: "🗓️", ex: "It is cold in December.", exJa: "12がつは さむいです。" },

  // ===== じかん =====
  { en: "today", ja: "きょう", emoji: "📆", ex: "I am happy today.", exJa: "きょうは うれしいです。" },
  { en: "tomorrow", ja: "あした", emoji: "📆", ex: "See you tomorrow.", exJa: "また あした。" },
  { en: "yesterday", ja: "きのう", emoji: "📆", ex: "I played soccer yesterday.", exJa: "きのう サッカーを しました。" },
  { en: "morning", ja: "あさ", emoji: "🌅", ex: "Good morning.", exJa: "おはよう ございます。" },
  { en: "afternoon", ja: "ごご", emoji: "🌤️", ex: "Good afternoon.", exJa: "こんにちは。" },
  { en: "evening", ja: "ゆうがた", emoji: "🌆", ex: "Good evening.", exJa: "こんばんは。" },
  { en: "night", ja: "よる", emoji: "🌙", ex: "Good night.", exJa: "おやすみなさい。" },
  { en: "weekend", ja: "しゅうまつ", emoji: "🎉", ex: "I like the weekend.", exJa: "わたしは しゅうまつが すきです。" },
  { en: "week", ja: "しゅう", emoji: "📅", ex: "See you next week.", exJa: "また らいしゅう。" },
  { en: "year", ja: "とし", emoji: "🎊", ex: "Happy new year.", exJa: "あけまして おめでとう。" },

  // ===== ようす(けいようし) =====
  { en: "big", ja: "おおきい", emoji: "🐘", ex: "The elephant is big.", exJa: "ぞうは おおきいです。" },
  { en: "small", ja: "ちいさい", emoji: "🐭", ex: "The mouse is small.", exJa: "ねずみは ちいさいです。" },
  { en: "long", ja: "ながい", emoji: "🐍", ex: "The snake is long.", exJa: "へびは ながいです。" },
  { en: "short", ja: "みじかい", emoji: "📏", ex: "My hair is short.", exJa: "わたしの かみは みじかいです。" },
  { en: "new", ja: "あたらしい", emoji: "✨", ex: "I have a new bag.", exJa: "あたらしい かばんを もっています。" },
  { en: "old", ja: "ふるい / としをとった", emoji: "🕰️", ex: "This book is old.", exJa: "この本ほんは ふるいです。" },
  { en: "good", ja: "よい", emoji: "👍", ex: "This is a good book.", exJa: "これは よい本ほんです。" },
  { en: "happy", ja: "うれしい", emoji: "😊", ex: "I am happy.", exJa: "わたしは うれしいです。" },
  { en: "sad", ja: "かなしい", emoji: "😢", ex: "I am sad.", exJa: "わたしは かなしいです。" },
  { en: "hot", ja: "あつい", emoji: "🥵", ex: "It is hot today.", exJa: "きょうは あついです。" },
  { en: "cold", ja: "さむい / つめたい", emoji: "🥶", ex: "It is cold today.", exJa: "きょうは さむいです。" },
  { en: "easy", ja: "かんたん", emoji: "😀", ex: "This test is easy.", exJa: "この テストは かんたんです。" },
  { en: "difficult", ja: "むずかしい", emoji: "😖", ex: "This test is difficult.", exJa: "この テストは むずかしいです。" },
  { en: "fast", ja: "はやい(スピード)", emoji: "🏃", ex: "The horse is fast.", exJa: "うまは はやいです。" },
  { en: "slow", ja: "おそい", emoji: "🐢", ex: "The turtle is slow.", exJa: "かめは おそいです。" },
  { en: "tall", ja: "せが たかい", emoji: "🦒", ex: "The giraffe is tall.", exJa: "きりんは せが たかいです。" },
  { en: "pretty", ja: "かわいい / きれい", emoji: "🌸", ex: "The flower is pretty.", exJa: "はなは きれいです。" },
  { en: "cute", ja: "かわいい", emoji: "🐶", ex: "The dog is cute.", exJa: "いぬは かわいいです。" },
  { en: "kind", ja: "しんせつ", emoji: "🤗", ex: "My teacher is kind.", exJa: "わたしの 先生せんせいは しんせつです。" },
  { en: "nice", ja: "すてき", emoji: "😊", ex: "You are nice.", exJa: "あなたは すてきです。" },
  { en: "beautiful", ja: "うつくしい", emoji: "🌅", ex: "The sunset is beautiful.", exJa: "ゆうやけは うつくしいです。" },
  { en: "hungry", ja: "おなかが すいた", emoji: "🍽️", ex: "I am hungry.", exJa: "わたしは おなかが すいています。" },
  { en: "thirsty", ja: "のどが かわいた", emoji: "🥤", ex: "I am thirsty.", exJa: "わたしは のどが かわいています。" },
  { en: "tired", ja: "つかれた", emoji: "😴", ex: "I am tired.", exJa: "わたしは つかれています。" },
  { en: "busy", ja: "いそがしい", emoji: "🏃‍♀️", ex: "My mother is busy.", exJa: "おかあさんは いそがしいです。" },
  { en: "favorite", ja: "いちばん すきな", emoji: "⭐", ex: "This is my favorite book.", exJa: "これは わたしの いちばん すきな本ほんです。" },

  // ===== どうし =====
  { en: "play", ja: "あそぶ / (スポーツを)する", emoji: "⚽", ex: "I play soccer.", exJa: "わたしは サッカーを します。" },
  { en: "study", ja: "べんきょうする", emoji: "📖", ex: "I study English.", exJa: "わたしは えいごを べんきょうします。" },
  { en: "like", ja: "すき", emoji: "❤️", ex: "I like dogs.", exJa: "わたしは いぬが すきです。" },
  { en: "have", ja: "もっている", emoji: "🖐️", ex: "I have a pen.", exJa: "わたしは ペンを もっています。" },
  { en: "go", ja: "いく", emoji: "🚶", ex: "I go to school.", exJa: "わたしは がっこうへ いきます。" },
  { en: "come", ja: "くる", emoji: "🙋", ex: "Come here.", exJa: "ここに きて。" },
  { en: "eat", ja: "たべる", emoji: "🍽️", ex: "I eat breakfast.", exJa: "わたしは あさごはんを たべます。" },
  { en: "drink", ja: "のむ", emoji: "🥤", ex: "I drink milk.", exJa: "わたしは ぎゅうにゅうを のみます。" },
  { en: "read", ja: "よむ", emoji: "📖", ex: "I read a book.", exJa: "わたしは 本ほんを よみます。" },
  { en: "write", ja: "かく", emoji: "✍️", ex: "I write my name.", exJa: "わたしは なまえを かきます。" },
  { en: "listen", ja: "きく", emoji: "👂", ex: "I listen to music.", exJa: "わたしは おんがくを ききます。" },
  { en: "look", ja: "みる", emoji: "👀", ex: "Look at this.", exJa: "これを みて。" },
  { en: "see", ja: "みえる", emoji: "👁️", ex: "I see a bird.", exJa: "とりが みえます。" },
  { en: "watch", ja: "みる(テレビなど)", emoji: "📺", ex: "I watch TV.", exJa: "わたしは テレビを みます。" },
  { en: "sing", ja: "うたう", emoji: "🎤", ex: "I sing a song.", exJa: "わたしは うたを うたいます。" },
  { en: "dance", ja: "おどる", emoji: "💃", ex: "I like to dance.", exJa: "わたしは おどるのが すきです。" },
  { en: "swim", ja: "およぐ", emoji: "🏊", ex: "I can swim.", exJa: "わたしは およげます。" },
  { en: "run", ja: "はしる", emoji: "🏃", ex: "I run fast.", exJa: "わたしは はやく はしります。" },
  { en: "walk", ja: "あるく", emoji: "🚶", ex: "I walk to school.", exJa: "わたしは あるいて がっこうへ いきます。" },
  { en: "jump", ja: "ジャンプする", emoji: "🤸", ex: "I can jump high.", exJa: "わたしは たかく ジャンプできます。" },
  { en: "cook", ja: "りょうりする", emoji: "🍳", ex: "I cook dinner.", exJa: "わたしは ばんごはんを つくります。" },
  { en: "wash", ja: "あらう", emoji: "🧼", ex: "I wash my hands.", exJa: "わたしは てを あらいます。" },
  { en: "help", ja: "てつだう", emoji: "🤝", ex: "I help my mother.", exJa: "わたしは おかあさんを てつだいます。" },
  { en: "open", ja: "あける", emoji: "📖", ex: "Open the door.", exJa: "ドアを あけて。" },
  { en: "close", ja: "しめる", emoji: "🚪", ex: "Close the door.", exJa: "ドアを しめて。" },
  { en: "use", ja: "つかう", emoji: "🖐️", ex: "I use a computer.", exJa: "わたしは コンピューターを つかいます。" },
  { en: "live", ja: "すむ", emoji: "🏠", ex: "I live in Tokyo.", exJa: "わたしは とうきょうに すんでいます。" },
  { en: "want", ja: "ほしい", emoji: "🙏", ex: "I want a new bike.", exJa: "わたしは あたらしい じてんしゃが ほしいです。" },
  { en: "know", ja: "しっている", emoji: "🧠", ex: "I know his name.", exJa: "わたしは かれの なまえを しっています。" },
  { en: "speak", ja: "はなす", emoji: "🗣️", ex: "I speak English.", exJa: "わたしは えいごを はなします。" },
  { en: "talk", ja: "はなす", emoji: "💬", ex: "I talk with my friend.", exJa: "わたしは ともだちと はなします。" },
  { en: "say", ja: "いう", emoji: "💬", ex: "Say hello.", exJa: "あいさつを して。" },
  { en: "ask", ja: "きく(たずねる)", emoji: "❓", ex: "I ask a question.", exJa: "わたしは しつもんを します。" },
  { en: "buy", ja: "かう", emoji: "🛍️", ex: "I buy a book.", exJa: "わたしは 本ほんを かいます。" },
  { en: "make", ja: "つくる", emoji: "🛠️", ex: "I make a cake.", exJa: "わたしは ケーキを つくります。" },
  { en: "get", ja: "える / うけとる", emoji: "🎁", ex: "I get a present.", exJa: "わたしは プレゼントを もらいます。" },
  { en: "give", ja: "あげる", emoji: "🎁", ex: "I give her a flower.", exJa: "わたしは かのじょに はなを あげます。" },
  { en: "take", ja: "とる / もっていく", emoji: "🖐️", ex: "Take my hand.", exJa: "わたしの てを とって。" },
  { en: "sit", ja: "すわる", emoji: "🪑", ex: "Please sit down.", exJa: "すわって ください。" },
  { en: "stand", ja: "たつ", emoji: "🧍", ex: "Please stand up.", exJa: "たって ください。" },
  { en: "sleep", ja: "ねる", emoji: "😴", ex: "I sleep at nine.", exJa: "わたしは 9じに ねます。" },

  // ===== ぎもんし・だいめいし =====
  { en: "what", ja: "なに", emoji: "❓", ex: "What is this?", exJa: "これは なんですか。" },
  { en: "who", ja: "だれ", emoji: "❓", ex: "Who is this?", exJa: "これは だれですか。" },
  { en: "when", ja: "いつ", emoji: "❓", ex: "When is your birthday?", exJa: "たんじょうびは いつですか。" },
  { en: "where", ja: "どこ", emoji: "❓", ex: "Where is my bag?", exJa: "わたしの かばんは どこですか。" },
  { en: "why", ja: "なぜ", emoji: "❓", ex: "Why are you sad?", exJa: "なぜ かなしいのですか。" },
  { en: "how", ja: "どうやって / どのくらい", emoji: "❓", ex: "How are you?", exJa: "げんきですか。" },
  { en: "which", ja: "どちら", emoji: "❓", ex: "Which is yours?", exJa: "どちらが あなたのですか。" },
  { en: "this", ja: "これ", emoji: "👉", ex: "This is my pen.", exJa: "これは わたしの ペンです。" },
  { en: "that", ja: "あれ", emoji: "👈", ex: "That is a cat.", exJa: "あれは ねこです。" },

  // ===== きほんご =====
  { en: "in", ja: "~の なかに", emoji: "📦", ex: "The cat is in the box.", exJa: "ねこは はこの なかに います。" },
  { en: "on", ja: "~の うえに", emoji: "📦", ex: "The book is on the desk.", exJa: "本ほんは つくえの うえに あります。" },
  { en: "under", ja: "~の したに", emoji: "📦", ex: "The cat is under the table.", exJa: "ねこは テーブルの したに います。" },
  { en: "at", ja: "~で", emoji: "📍", ex: "I am at school.", exJa: "わたしは がっこうに います。" },
  { en: "with", ja: "~と いっしょに", emoji: "🤝", ex: "I play with my friend.", exJa: "わたしは ともだちと あそびます。" },
  { en: "from", ja: "~から", emoji: "➡️", ex: "I am from Japan.", exJa: "わたしは にほんの しゅっしんです。" },
  { en: "please", ja: "どうぞ / おねがいします", emoji: "🙏", ex: "Please help me.", exJa: "たすけて ください。" },
  { en: "very", ja: "とても", emoji: "❗", ex: "I am very happy.", exJa: "わたしは とても うれしいです。" },
  { en: "and", ja: "~と", emoji: "➕", ex: "I like dogs and cats.", exJa: "わたしは いぬと ねこが すきです。" },
  { en: "yes", ja: "はい", emoji: "✅", ex: "Yes, I do.", exJa: "はい、そうです。" },
  { en: "no", ja: "いいえ", emoji: "❌", ex: "No, I don't.", exJa: "いいえ、ちがいます。" },
];

// ゾーンは 10ごずつ 自動で わりあて
WORD_LIST.forEach((w, i) => {
  w.id = i;
  w.zone = Math.floor(i / 10) + 1;
});

const TOTAL_ZONES = Math.ceil(WORD_LIST.length / 10);
